name: scp
description: Mobile app of ICS NIT Rourkela

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.5.7
  cloud_firestore: ^0.12.9+6
  connectivity: ^0.4.9+3
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.11.1
  firebase_crashlytics: ^0.1.0+2
  firebase_database: ^3.0.3
  firebase_messaging: ^5.1.6
  firebase_remote_config: ^0.2.0+3
  firebase_storage: ^3.0.8
  flutter_webview_plugin: ^0.3.11
  font_awesome_flutter: ^8.10.0
  get_it: ^5.0.3
  http: ^0.12.0+2
  in_app_review: ^1.0.4
  intl: ^0.15.2
  lite_rolling_switch: ^0.1.1
  lottie: ^0.7.0+1
  native_contact_dialog: ^0.2.2
  ndialog: ^3.1.0
  package_info: ^0.4.3+2
  path_provider: ^1.0.0
  pin_code_text_field: ^1.3.7
  rate_my_app: ^0.7.2
  shared_preferences: ^0.5.3+4
  table_calendar: ^2.2.3
  url_launcher: ^5.1.0
  graphql_flutter: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"
flutter_icons:
  ios: true
  image_path: 'assets/icon/icon.png'

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: PfDin
      fonts:
        - asset: fonts/pf_din.otf
        - asset: fonts/pf_din_med.ttf
          weight: 500
