name: Codemagic status

on: pull_request

jobs:
  codemagic_comment:
    runs-on: ubuntu-latest
    name: Codemagic build
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: '[![Codemagic build status](https://api.codemagic.io/apps/5f0f5dd5d0eccd000cd36532/5f0f5dd5d0eccd000cd36531/status_badge.svg)](https://codemagic.io/apps/5f0f5dd5d0eccd000cd36532/5f0f5dd5d0eccd000cd36531/latest_build)'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
